CapaPrecentacionEquipos/Controllers/EquiposController.cs
using ActivoFijo.Models;
using DocumentFormat.OpenXml.Bibliography;
using Irony.Parsing;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace CapaPrecentacionEquipos.Controllers
{
    public class EquiposController : Controller
    {
        // GET: Equipos
        public ActionResult Index()
        {
            return View();
        }

        //Detalle de Equipos
        public ActionResult DetalleEquipo(int idequipo = 0)
        {
            Equipo oEquipo = new Equipo();
            bool conversion;
            oEquipo = new CN_Equipo().Listar().Where(p => p.IdEquipos == idequipo).FirstOrDefault();

            if (oEquipo != null)
            {
                oEquipo.Base64 = CN_Recursos.ConvertirBase64(Path.Combine(oEquipo.RutaImagen, oEquipo.NombreImagen), out conversion);
                oEquipo.Extension = Path.GetExtension(oEquipo.NombreImagen);
            }

            return View(oEquipo);
        }


        [HttpGet]
        public JsonResult ListCategoria()
        {
            List<Categoria> lista = new List<Categoria>();
            lista = new CN_Categoria().Listar();

            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult ListaMarcaporCategoria(int idcategoria)
        {
            List<Marca> lista = new List<Marca>();

            lista = new CN_Marca().listarMarcaporCategoria(idcategoria);

            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ListarEquipo(int idcategoria, int idmarca)
        {
            List<Equipo> lista = new List<Equipo>();

            bool conversion;

            lista = new CN_Equipo().Listar().Select(p => new Equipo()
            {
                IdEquipos = p.IdEquipos,
                Nombre = p.Nombre,
                Descripcion = p.Descripcion,
                oMarca = p.oMarca,
                oCategoria = p.oCategoria,
                oRazonSocial = p.oRazonSocial,
                Serie = p.Serie,
                Precio = p.Precio,
                Stock = p.Stock,
                RutaImagen = p.RutaImagen,
                Base64 = CN_Recursos.ConvertirBase64(Path.Combine(p.RutaImagen, p.NombreImagen), out conversion),
                Extension = Path.GetExtension(p.NombreImagen),
                Activo = p.Activo
            }).Where(p =>
                p.oCategoria.IdCategoria == (idcategoria == 0 ? p.oCategoria.IdCategoria : idcategoria) &&
                p.oMarca.IdMarca == (idmarca == 0 ? p.oMarca.IdMarca : idmarca) &&
                p.Stock > 0 && p.Activo == true
            ).ToList();

            var jsonresult = Json(new { data = lista }, JsonRequestBehavior.AllowGet);
            jsonresult.MaxJsonLength = int.MaxValue;

            return jsonresult;

        }

        public ActionResult Carrito()
        {
            return View();
        }

        // AGREGAR CARRITO
        [HttpPost]
        public JsonResult AgregarCarrito(int idequipo)
        {
            int idusuario = ((Usuario)Session["Usuario"]).IdUsuario;

            bool existe = new CN_Carrito().ExisteCarrito(idusuario, idequipo);

            bool respuesta = false;

            string mensaje = string.Empty;

            if (existe)
            {
                mensaje = "El equipo ya existe en el carrito";
            }
            else
            {
                respuesta = new CN_Carrito().OperacionCarrito(idusuario, idequipo, true, out mensaje);
            }
            return Json(new { respuesta = respuesta, mensaje = mensaje });
        }


        [HttpGet]
        public JsonResult CatidadEnCarrito()
        {
            int idusuario = ((Usuario)Session["Usuario"]).IdUsuario;
            int cantidad = new CN_Carrito().CantidadEnCarrito(idusuario);
            return Json(new { cantidad = cantidad }, JsonRequestBehavior.AllowGet);
        }

        // CREAR UN METODO POST LISTAR PRODUCTO
        [HttpPost]
        public JsonResult ListarProductosCarrito()
        {
            int idusuario = ((Usuario)Session["Usuario"]).IdUsuario;

            List<Carrito> oLista = new List<Carrito>();

            bool conversion;

            oLista = new CN_Carrito().ListarEquipo(idusuario).Select(oc => new Carrito()
            {
                oEquipo = new Equipo()
                {
                    IdEquipos = oc.oEquipo.IdEquipos,
                    Nombre = oc.oEquipo.Nombre,
                    oMarca = oc.oEquipo.oMarca,
                    Precio = oc.oEquipo.Precio,
                    RutaImagen = oc.oEquipo.RutaImagen,
                    Base64 = CN_Recursos.ConvertirBase64(Path.Combine(oc.oEquipo.RutaImagen, oc.oEquipo.Nombre), out conversion),
                    Extension = Path.GetExtension(oc.oEquipo.NombreImagen)
                },
                Cantidad = oc.Cantidad
            }).ToList();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult OperacionCarrito(int idequipo, bool sumar)
        {
            int idusuario = ((Usuario)Session["Usuario"]).IdUsuario;

            bool existe = new CN_Carrito().ExisteCarrito(idusuario, idequipo);

            bool respuesta = false;

            string mensaje = string.Empty;

            respuesta = new CN_Carrito().OperacionCarrito(idusuario, idequipo, true, out mensaje);

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarCarrito(int idequipo)
        {
            int idusuario = ((Usuario)Session["Usuario"]).IdUsuario;

            bool respuesta = false;

            string mensaje = string.Empty;

            respuesta = new CN_Carrito().EliminarCarrito(idusuario, idequipo);

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        //Obtener MarcaTienda
        public JsonResult ObtenerMarcaTienda()
        {
            List<MarcaTienda> oLista = new List<MarcaTienda>();

            oLista = new CN_Asignado().ObtenerMarcaTienda();

            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ObtenerTienda(string idmarcatienda)
        {
            List<Tienda> oLista = new List<Tienda>();

            oLista = new CN_Asignado().ObtenerTienda(idmarcatienda);

            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ObtenerTecnico()
        {
            List<Tecnico> oLista = new List<Tecnico>();

            oLista = new CN_Asignado().ObtenerTecnico();

            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ListarEquipoCarrito()
        {
            int idusuario = ((Usuario)Session["Usuario"]).IdUsuario;

            List<Carrito> oLista = new List<Carrito>();

            bool conversion;

            oLista = new CN_Carrito().ListarEquipo(idusuario).Select(oc => new Carrito()
            {
                oEquipo = new Equipo()
                {
                    IdEquipos = oc.oEquipo.IdEquipos,
                    Nombre = oc.oEquipo.Nombre,
                    oMarca = oc.oEquipo.oMarca,
                    Precio = oc.oEquipo.Precio,
                    RutaImagen = oc.oEquipo.RutaImagen,
                    Base64 = CN_Recursos.ConvertirBase64(Path.Combine(oc.oEquipo.RutaImagen, oc.oEquipo.NombreImagen), out conversion),
                    Extension = Path.GetExtension(oc.oEquipo.NombreImagen)
                },
                Cantidad = oc.Cantidad
            }).ToList();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> ProcesarPago(List<Carrito> oListaCarrito, Venta oVenta)
        {
            decimal total = 0;

            DataTable detalle_venta = new DataTable();
            detalle_venta.Locale = new CultureInfo("es-PE");
            detalle_venta.Columns.Add("IdEquipos", typeof(string));
            detalle_venta.Columns.Add("Cantidad", typeof(int));
            detalle_venta.Columns.Add("Total", typeof(decimal));

            foreach (Carrito oCarrito in oListaCarrito)
            {
                decimal subtotal = Convert.ToDecimal(oCarrito.Cantidad.ToString()) * oCarrito.oEquipo.Precio;

                total += subtotal;
                detalle_venta.Rows.Add(new object[]
                {
                    oCarrito.oEquipo.IdEquipos,
                    oCarrito.Cantidad,
                    subtotal,
                });

            }

            oVenta.MontoTotal = total;
            oVenta.IdUsuario = ((Usuario)Session["Usuario"]).IdUsuario;

            TempData["Venta"] = oVenta;
            TempData["DetalleVenta"] = detalle_venta;

            return Json(new { Status = true, Link = "/Equipos/Pagoefectuado?idTransaccion=code0001&status=true" }, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> PagoEfectuado()
        {
            string idtransaccion = Request.QueryString["idTransaccion"];
            bool status = Convert.ToBoolean(Request.QueryString["status"]);

            ViewData["Status"] = status;

            if (status)
            {
                Venta oVenta = (Venta)TempData["Venta"];

                DataTable detalle_venta = (DataTable)TempData["DetalleVenta"];

                oVenta.IdTransaccion = idtransaccion;

                string mensaje = string.Empty;

                bool respuesta = new CN_Venta().Registrar(oVenta, detalle_venta, out mensaje);

CapaPrecentacionEquipos/Views/Equipos/DetalleEquipo.cshtml
@model ActivoFijo.Models.Equipo
@{
    ViewBag.Title = "DetalleEquipo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="data:image/@Html.DisplayTextFor(m => m.Extension);base64,@Html.DisplayTextFor(m => m.Base64)" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">Marca: @Html.DisplayTextFor(m => m.oMarca.Descripcion)</div>
                <h1 class="display-5 fw-bolder">@Html.DisplayTextFor(m => m.Nombre)</h1>
                <div class="fs-5 mb-5">
                    <span>@Html.DisplayTextFor(m => m.Precio) Soles</span>
                </div>
                <p class="lead">@Html.DisplayTextFor(m => m.Descripcion)</p>
                <div class="d-flex">
                    <a href="@Url.Action("Index", "Equipos")" class="btn btn-danger w-50 text-center me-3">
                        <i class="fas fa-undo-alt"></i> Volver
                    </a>

                    @if (Session["Usuario"] != null)
                    {
                        <button class="btn btn-outline-success agregarcarrito flex-shink-0 w-50" type="button" data-idquipo="@Html.DisplayFor(m => m.IdEquipos)">
                            <i class="fas fa-cart-plus"></i> Agregar al carrito
                        </button>
                    }


                </div>
            </div>
        </div>
    </div>
</section>

@section scripts {
    <script>
        $(document).on("click", "button.agregarcarrito", function () {
            console.log($(this).data("idquipo"));

            jQuery.ajax({
                url: '@Url.Action("AgregarCarrito", "Equipos")',
                type: "POST",
                data: JSON.stringify({ idequipo: $(this).data("idquipo") }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data.respuesta) {
                        MostrarCantidadCarrito();

                        swal("", "Agregado al Carrito", "success");
                    } else {
                        swal("", data.mensaje, "warning");
                    }
                }
            });
        });
    </script>
}

CapaPrecentacionEquipos/Views/Equipos/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Asignación de Equipos</h1>
            <p class="lead fw-normal text-white-50 mb-0">Encuentra tu Equipo</p>
        </div>
    </div>
</header>
<!-- Section-->
<section>
    <div class="container-fluid px-5 my-5">
        <div class="row">
            <div class="col-sm-3">

                <div class="row mb-3">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header bg-dark text-white">
                                Catgoria
                            </div>
                            <div id="contenedor_categoria" class="card-body">

                            </div>
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header bg-dark text-white">
                                Marcas
                            </div>
                            <div id="contenedor_marca" class="card-body">

                            </div>
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-sm-12">
                        <div class="d-grid gap-2">
                            <button id="btnaplicarfiltro" class="btn btn-outline-dark btn-block" type="button">
                                <i class="fas fa-filter"></i>Aplicar filtros
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-9">
                <div id="contenedor_producto" class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Fancy Product</h5>
                                    <!-- Product price-->
                                    S/40.00 - S/80.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Special Item</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!-- Product price-->
                                    <span class="text-muted text-decoration-line-through">S/20.00</span>
                                    $18.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
</section>

@section scripts {

    
    

    <script>

        function ObtenerRutaCompletaImagen(ruta, nombreImagen) {
            return ruta + '/' + nombreImagen;
        }

        $(document).ready(function () {
            MostrarCategorias();
            MostrarEquipo(0,0);
        })

        // Mostrar Categoria
        function MostrarCategorias() {
            jQuery.ajax({
                url: "@Url.Action("ListCategoria", "Equipos")",
                type: "GET",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    $("#contenedor_categoria").LoadingOverlay("hide");

                    $("<div>").addClass("form-check").append(
                        $("<input>").addClass("form-check-input").attr({ "type": "radio", "name": "categoria", "value": "0", "id": "cx", "checked": "checked" }),
                        $("<label>").addClass("from-check-label").text("Todos").attr({ "for": "cx" })
                    ).appendTo("#contenedor_categoria")

                    $.each(response.data, function (i, element) {
                        $("<div>").addClass("form-check").append(

                            $("<input>").addClass("form-check-input").attr({ "type": "radio", "name": "categoria", "value": element.IdCategoria, "id": "c" + i }),
                            $("<label>").addClass("from-check-label").text(element.Descripcion).attr({ "for": "c" + i })
                        ).appendTo("#contenedor_categoria")
                    })
                    MostrarMarca();
                },
                beforeSend: function () {
                    $("#contenedor_categoria").LoadingOverlay("show");
                }
            })
        }

        // Mostrar Marca

        function MostrarMarca() {
            var _idcategoria = $("input[name=categoria]:checked").val();


            jQuery.ajax({
                url: "@Url.Action("ListaMarcaporCategoria", "Equipos")",
                type: "POST",
                data: JSON.stringify({ idcategoria: _idcategoria }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    $("#contenedor_marca").html("");
                    $("#contenedor_marca").LoadingOverlay("hide");

                    $("<div>").addClass("form-check").append(

                        $("<input>").addClass("form-check-input").attr({ "type": "radio", "name": "marca", "value": "0", "id": "mx", "checked": "checked" }),
                        $("<label>").addClass("from-check-label").text("Todos").attr({ "for": "mx" })
                    ).appendTo("#contenedor_marca")

                    $.each(response.data, function (i, element) {
                        $("<div>").addClass("form-check").append(

                            $("<input>").addClass("form-check-input").attr({ "type": "radio", "name": "marca", "value": element.IdMarca, "id": "m" + i }),
                            $("<label>").addClass("from-check-label").text(element.Descripcion).attr({ "for": "m" + i })
                        ).appendTo("#contenedor_marca")
                    })
                },
                beforeSend: function () {
                    $("#contenedor_marca").LoadingOverlay("show");
                }
            })
        }

        $(document).on("change", "input[name=categoria]", function () {
            MostrarMarca();


        })

        function MostrarEquipo(_idcategoria, _idmarca) {

            jQuery.ajax({
                url: "@Url.Action("ListarEquipo", "Equipos")",
                type: "POST",
                data: JSON.stringify({ idcategoria: _idcategoria, idmarca: _idmarca }), // Corrige el nombre del parámetro
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    $("#contenedor_producto").html(""); // Limpia el contenedor antes de agregar nuevos elementos
                    $("#contenedor_producto").LoadingOverlay("hide");

                    $.each(response.data, function (i, element) {
                        $("<div>").addClass("col mb-5").append(
                            $("<div>").addClass("card h-100").append(
                                $("<img>").addClass("card-img-top").attr({ "src": "data:image/" + element.Extension + ";base64," + element.Base64 }),
                                $("<div>").addClass("card-body p-4").append(
                                    $("<div>").addClass("text-center").append(
                                        $("<h5>").addClass("fw-bolder").text(element.Nombre),
                                        $("<p>").text("Razón Social: " + element.oRazonSocial.NomRazonSocial),
                                        "S/ " + element.Precio.toFixed(2) 
                                    )
                                ),
                                $("<div>").addClass("card-footer p-2 pt-0 border-top-0 bg-transparent").append(


                                    $("<div>").addClass("d-grid gap-2").append(
                                        @if (Session["Usuario"]!=null)
                                         {
                                             @:$("<button>").addClass("btn btn-success mt-auto agregarcarrito").data("idequipo", element.IdEquipos).text("Agregar al carrito"),
                                         }

                                        $("<a>").addClass("btn btn-dark mt-auto btn-ver-detalle")
                                           .attr({ "href": "@Url.Action("DetalleEquipo", "Equipos")" + "?idequipo=" + element.IdEquipos })
                                           .text("Ver detalle")
                                    )


                                )

                            )
                        ).appendTo("#contenedor_producto")
                    });
                },
                beforeSend: function () {
                    $("#contenedor_producto").LoadingOverlay("show");
                }
            });
        }


        $("#btnaplicarfiltro").click(function () {

            var _idcategoria = $("input[name=categoria]:checked").val()
            var _idmarca = $("input[name=marca]:checked").val()
            MostrarEquipo(_idcategoria, _idmarca)

        })


        $(document).on("click", "button.agregarcarrito", function () {
            console.log($(this).data("idequipo"))
        
            jQuery.ajax({
                url: '@Url.Action("AgregarCarrito", "Equipos")',
                type: "POST",
                data: JSON.stringify({ idequipo: $(this).data("idequipo") }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data.respuesta) {
                        MostrarCantidadCarrito();
        
                        swal({
                            title: "Agregado al carrito",
                            text: "¿Desea ir al carrito?",
                            type: "success",
                            showCancelButton: true,
                            confirmButtonText: "Si",
                            cancelButtonText: "No",
                            closeOnConfirm: true
                        }, function () {
                            window.location.href = '@Url.Action("Carrito", "Equipos")'
                        })
                    } else {
                        swal("", data.mensaje, "warning");
                    }
                }
            })
        })


    </script>

}

CapaPrecentacionEquipos/Views/Equipos/PagoEfectuado.cshtml
@{
    ViewBag.Title = "PagoEfectuado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-sm-12 text-center">
        <br /><br />

        @{

            if ((bool)ViewData["Status"])
            {
                <h1 class="text-success">Gracias!</h1>
                <i class="far fa-check-circle fa-9x text-success"></i>

                <h2 class="text-success">Su registro fue realizado con exito</h2>
                <h4> ID de Transaccion : @ViewData["IdTransaccion"] </h4>

                <br />

                <a href="@Url.Action("Index", "Equipos")" class="btn btn-primary">Regresar para seguir asignado Equipos</a>

            }
            else
            {
                <h1 class="text-danger">Lo sentimos</h1>

                <i class="fas fa-exclamation"></i>

                <h2 class="text-danger">Su registro no fue realizado</h2>

                <br />
                <a href="@Url.Action("Index", "Equipos")" class="btn btn-primary">Regresar para seguir asignado Equipos</a>
            }

        }

    </div>
</div>